language: node_js
sudo: required

services:
  - docker

before_install:
  - docker build -t TimParx/docker-react-f -f Dockerfile.dev .

script:
  - docker run TimParx/docker-react-f npm run test -- --coverage